version: "3"
services:
  restify:
    build: .
    ports:
      - 3030:3030
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restify
      MYSQL_USER: sai
      MYSQL_PASSWORD: supersecret
    ports:
      - 3307:3306
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:

networks:
  default:
    external:
      name: restify-docker-network
