apiVersion: v1
kind: Pod
metadata:
  name: restify
  labels:
    name: restify
spec:
  containers:
    - name: restify
      image: saiwaimaung/restify:latest
      livenessProbe:
        httpGet:
          path: /healthy
          port: 3030
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 3030
          name: http
          protocol: TCP
